### ISSUE TITLE
UnityNMFighter starting the fight

### ISSUE THREAD

**Issue by Sinnersslayer** [DanielHazzard/Ashita-Addons#1]
Hi Daniel,

First of all THANKS for this addon.
I have run into an issue where addon doesn't start the fight.
Here is step by step what's happening.
1) addon targets the Junction
2) press Enter
3) Menu shows up but instead of pressing UP he use Escape first for some reason when menu disappears it presses UP because I see my camera move.
4) a message "no confrontation" shows up on the screen

Addon gives fatal error while using /unmf engagetype 1 command
![pol_2018-03-09_09-01-11](https://user-images.githubusercontent.com/33654112/37196904-dc9509cc-2378-11e8-9375-f41006a7fd37.jpg)

**Comment by DanielHazzard** [comment]
Okay, was this after the recent change I made as I increased the time it'd wait until it presses enter to allow it to press UP?

I'll look into the engagetype 1 error.

EDIT:

I made changes to the LUA please update and see if this fixes your errors. Thank you for the bug report.

**Comment by Sinnersslayer** [comment]
I have updated but it's still the same.
He targets Junction, presses Enter, menu shows up for one second and disappears like when you press Escape and then my camera moves like you would press UP.

**Comment by DanielHazzard** [comment]
You need to adjust the timers in this area until you find one that works.

```lua
            openEnter()
            ashita.timer.once(0.5, closeEnter)
            ashita.timer.once(2.0, openEnter)
            ashita.timer.once(2.3, closeEnter)
            ashita.timer.once(2.7, advanceUpOpen)
            ashita.timer.once(3.2, advanceUpClose)
            ashita.timer.once(4.7, openEnter)
            ashita.timer.once(5.0, closeEnter)
            ashita.timer.once(5.3, releaseKeys)
```

I can keep changing it myself, but it'll probably be easier for you to do it as you can keep reloading and checking.

**Comment by Sinnersslayer** [comment]
Isn't 
> ashita.timer.once(2.3, closeEnter)

useless here?
The procedure should look like this:
1) target
2) ashita.timer.once(0.5, closeEnter)
3) ashita.timer.once(2.0, openEnter)
4) ashita.timer.once(2.7, advanceUpOpen)
5) ashita.timer.once(3.2, advanceUpClose)
6) ashita.timer.once(4.7, openEnter)
7) ashita.timer.once(5.0, closeEnter)
8) ashita.timer.once(5.3, releaseKeys)

It looks like he hits enter second time on "Not yet!" and that why menu disappears.

**Comment by Sinnersslayer** [comment]
I have adjusted times to even 5 seconds but he seems not recognizin UP command and it hits ENTER again making menu to disappear and then he hist UP.
Is 

> advanceUpOpen 

a correct variable?

**Comment by DanielHazzard** [comment]
```lua
      openEnter() -- Press ENTER  to start after it's targeted
            ashita.timer.once(0.5, closeEnter) -- close first ENTER

            ashita.timer.once(2.0, openEnter) -- Press second ENTER for the Ready to begin? command
            ashita.timer.once(2.3, closeEnter) -- Close second ENTER

            ashita.timer.once(2.7, advanceUpOpen) -- Press UP to target Let's go!
            ashita.timer.once(3.2, advanceUpClose) -- close UP

            ashita.timer.once(4.7, openEnter) -- Press ENTER on Let's go!
            ashita.timer.once(5.0, closeEnter) -- Close last ENTER

            ashita.timer.once(5.3, releaseKeys) -- Release keys in case a previous Close did not activate
```

**Comment by DanielHazzard** [comment]
You don't have Enternity active do you?

**Comment by Sinnersslayer** [comment]
I do :smiley:

**Comment by DanielHazzard** [comment]
That's the problem then. Enternity is skipping the second ENTER's need, thus when it goes to push the second ENTER it exits, I'll push a release where you can have the option of ENTERINITY can you try that version.

Remember to set the ENTERNITY settings to yes.

**Comment by DanielHazzard** [comment]
Okay, pushed the new update, please let me know if it fixes the problem.

**Comment by Sinnersslayer** [comment]
I have removed Enternity addon, updated to the latest version, work beautifully so far.
I am close to 99 999 sparks cap so I will also check warp out option.
