### ISSUE TITLE
Gives error after reaching 99999 sparks

### ISSUE THREAD

**Issue by Sinnersslayer** [DanielHazzard/Ashita-Addons#2]
Have experienced a new error.
When used /unmf start, got this error.
![glizdus_2018 03 10_194429](https://user-images.githubusercontent.com/33654112/37245739-1f978ff4-249d-11e8-9673-44ae0eb4c4b0.png)

Also I have left bot running and after he got to the spark cap, something crashed too.
I am trying to reproduce this error message.

-EDIT-
Can't make it to give me an error, which he gave before.
Killed a NM under spark cap and after the fight he started to use coffers.
Which as a matter of fact I don't want to be used :smile:  
It gives an error too when I run out of inv space.
Will post it when I get it.

-EDIT 2-
I filled my inv with stuff and with 80/80 inv he still tries to use coffers and I can;t stop it...
/unmf stop doesn't work.

-EDIT 3-
He eventually stopped trying to use coffers when I moved them to Mog Case and gave me this error:
![glizdus_2018 03 10_201047](https://user-images.githubusercontent.com/33654112/37245897-64a444e6-249f-11e8-9fc0-51865a7ccc15.png)

I have turned off coffers from being used in config.

**Comment by Sinnersslayer** [comment]
Got another error after another fight WITH sparks cap.
IDK what bot is trying to do, think he want to warp.
I have warp ring turned on for warp

![glizdus_2018 03 10_201522](https://user-images.githubusercontent.com/33654112/37245923-139332be-24a0-11e8-959e-a957fe18e7d7.png)

> -- 0 = None, 1 = Ring, 2 = Scroll, 3 = Spell
variables.WarpMethod = 1


PS. Sorry for posting everything in one topic, but I have no idea to which part of the script this error is connected.

**Comment by DanielHazzard** [comment]
Okay, thank you, I'll look into all of them now.

**Comment by DanielHazzard** [comment]
Okay, pushed a fix for a few of these bugs.

**Comment by Sinnersslayer** [comment]
Having this "216" error again on capped sparks.
Also could You make it possible for addon to /shutdown game after getting spark cap?

**Comment by DanielHazzard** [comment]
Okay, I'll look into both tomorrow.

**Comment by Sinnersslayer** [comment]
You forgot about the ticket? ;)

**Comment by DanielHazzard** [comment]
No, I updated the file the day after.

Latest commit 4fbf75b 11 days ago

**Comment by Sinnersslayer** [comment]
Got something new but IDK when it accured as I was AFK and saw this error when I came back.
But I have no idea why he tried to use coffers when I didn't started farming them at all.

![glizdus_2018 03 31_065638](https://user-images.githubusercontent.com/33654112/38162868-6ba0c12a-34e9-11e8-964d-b9fba2d4abb1.png)

**Comment by DanielHazzard** [comment]
Okay, thanks, I'll look into it.

**Comment by Sinnersslayer** [comment]
Still getting errors when I hit cap
Bot doesn't warping me out and I have to reloaded it after each error.

**Comment by DanielHazzard** [comment]
Oh, completely forgot to look into that, sorry, I'll fix CurePlease, then try to see if I can see the problem.

**Comment by DanielHazzard** [comment]
Updated the LUA. Please let me know if it's still bugged.

**Comment by Sinnersslayer** [comment]
Sorry for keeping you waiting.
Unfortunately it still gives the same (216) error

https://user-images.githubusercontent.com/33654112/37245897-64a444e6-249f-11e8-9fc0-51865a7ccc15.png

**Comment by Sinnersslayer** [comment]
Funny thing is that when I was in CP party and eventualy hit the spark cap, it attempted to use a warp ring without any error...
This makes this error even more difficult to track.

**Comment by Sinnersslayer** [comment]
Ok I have found a way around it untill You find a proper solution for this.
Used OnEvent tool and when **_(216) error_** occurres it executes simple warp script I wrote ;)
Works so far.
