### ISSUE TITLE
Makes me die occasionally

### ISSUE THREAD

**Issue by Sinnersslayer** [DanielHazzard/Ashita-Addons#4]
It's hard to reproduce this error since it happens VERY rarely but sometimes when I come back to my keyboard I'm finding my char dead.
It's probably because of the bot spawning the NM but not engaging it.
I have ended up using external app with aggro detection and auto-facing the mob.

If it's possible, please implement facing check in the script and re-check engaging procedure.

**Comment by DanielHazzard** [comment]
Will do.
