### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by joebinne** [DanielHazzard/Ashita-Addons#7]
Hi Daniel, no problem with the Rolltracker addon but I would like to suggest to maybe add the lucky and unlucky roll on the text prompt somewhere so we know when to +1 or stop rolling? Something like => Samurai Roll (5, 7)  [**6**]  (Unlucky!) (+24 Store TP).

Maybe add the lucky in green and unlucky in red near the name of the roll? I don't know if it makes sense.. thanks! :)

**Comment by DanielHazzard** [comment]
Should already, I'll check why it doesn't.

**Comment by DanielHazzard** [comment]
I've realised, I misunderstood you, I'll sort this out, sorry about that.

**Comment by joebinne** [comment]
Thanks! 😊

**Comment by DanielHazzard** [comment]
Okay, edited, should now include it so long as you edit the option in the lua:

EnableLuckyUnluckyDisplay = false 

set as true

**Comment by joebinne** [comment]
You are the best
