### ISSUE TITLE
Error failed to call event timerpulse. lua:216 attempt to call global event 'print'...

### ISSUE THREAD

**Issue by Tru14** [DanielHazzard/Ashita-Addons#8]
Have been using this for years with no issue. Changed the UNM to Joyous Green for the first time. On initial load of the addon it performs as it should by popping the NM. However, as soon as the NM dies I get the above error and the addon is non-functional at that point and needs a reload. Even after a reload it continues to fail after the first kill.

**Comment by Tru14** [comment]
After further looking into the addon it looks like it's meant to stop after capped sparks which I assume is the reason for the error. Can this be removed or can a command be added to continue popping after capped sparks considering there is no way to spent sparks after initial cap these days?

**Comment by DanielHazzard** [comment]
I'll make modifications to it.
