### ISSUE TITLE
AutoBurst not working

### ISSUE THREAD

**Issue by jschaum** [DanielHazzard/Ashita-Addons#9]
### I have followed the installation instructions but AutoBurst doesnt do anything. I have tried adjusting the delay in the config file and still nothing. When i turn on debug mode i get no messages except if i weaponskill it says "weaponskill located." 

Edit: Attmepting to MB on SCH/RDM, Using Ashita

Next Edit: If i close the SC it works properly, im guessing this isnt designed to work with trust skillchains? I apologize if that is the case then and I have created a ticket for something the addon is not meant to do.

**Comment by DanielHazzard** [comment]
Pushed a fix.
